
name: Artifact trans beween jobs test

on:
  push:
    branches: [ "artifact" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: generate outputs
      run: |
        mkdir artifact
        echo $(pwd) >> artifact/1.txt
        echo $(whoami) >> artifact/1.txt
        echo $(date) >> artifact/1.txt
        ls -alh >> artifact/1.txt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifact  #final output name
        path: |
          artifact
  consume:
    runs-on: ubuntu-latest
    needs: ["generate"]
    steps:
    - name: download artifacts last job
      uses: actions/download-artifact@v4
      with:
        name: dist-artifact #last job's final output name
    - name: verify downloaded artifacts last job
      run: |
        cat 1.txt
        echo "# [end] read content from artifact from last job:">>  $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        cat 1.txt >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >>  $GITHUB_STEP_SUMMARY
    
