
name: Artifact trans beween jobs test

on:
  push:
    branches: [ "artifact" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: generate outputs
      run: |
        mkdir artifact
        echo $(pwd) >> artifact/1.txt
        echo $(ls -alh) >> artifact/1.txt
        echo $(whoami) >> artifact/1.txt
        echo $(date) >> artifact/1.txt
    - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: |
            artifact
  