name: Publish package to GitHub Packages
on:
  push:
    branches: [ "maven-package" ]
  release:
    branches: [ "maven-package" ]
    types: [created]
# test
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Publish package
        run: |
#         cd action-upload-java-packages
               cd java
         mvn package -P github
         mvn --batch-mode deploy -P github 

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
