# https://docs.github.com/en/actions

name: "native graalvm"

on:
  push:
    branches: [ "native-graalvm" ]
  pull_request:
    branches: [ "native-graalvm" ]

jobs:
  build-native-image:
    name: SpringBoot Native Application on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'


      - name: Build with Maven
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          cd java
          mvn --batch-mode -Pnative native:compile

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          name: demo-${{ matrix.os }}
          path: java/target*