# https://docs.github.com/en/actions

name: "native graalvm"

on:
  push:
    branches: [ "native-graalvm" ]
  pull_request:
    branches: [ "native-graalvm" ]

jobs:
  build-native-image:
    name: SpringBoot Native Application on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        # os: [windows-latest, ubuntu-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'


      - name: Build with Maven
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          cd java
          mvn --batch-mode -Pnative native:compile
      - run: cd java && mkdir staging && cp target/demo* staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: java/staging

      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/demo
      #     asset_name: demo-${{ matrix.os }}
      #     tag: ${{ github.ref }}